config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#about'
  get '/search', to: 'static_pages#search'
  get '/profiles', to: 'static_pages#profiles'
  resources :search_terms, except: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :search_term
  validates :page_number, presence: true
  validates :search_term_id, presence: true
end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :email, presence: true, uniqueness: true

  def self.search(term)
    if term
      self.where('email ILIKE ?', "%#{term}%").or(self.where('title ILIKE ?', "%#{term}%"))
    else
      self.all
    end
  end
end

app/models/search_term.rb
class SearchTerm < ApplicationRecord
  require 'roo'

  has_one :bookmark, dependent: :destroy
  validates :query, presence: true, uniqueness: true

  def self.import(file)
    spreadsheet = Roo::Spreadsheet.open(file.path)
    (spreadsheet.first_row..spreadsheet.last_row).each do |i|
      term = spreadsheet.row(i)
      SearchTerm.create(query: term[0])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/search_terms_controller.rb
class SearchTermsController < ApplicationController
  before_action :set_search_term, only: [:edit, :update, :destroy]

  def index
    @search_terms = SearchTerm.all.order(searched: :asc).paginate(:page => params[:page], :per_page => 30)
  end


  def new
    @search_term = SearchTerm.new
  end

  def edit
  end

  def create
    if params[:file]
      SearchTerm.import(params[:file])
      redirect_to search_terms_url, notice: 'File was imported.'
    else
      @search_term = SearchTerm.new(search_term_params)
      if @search_term.save
        redirect_to search_terms_url, notice: 'Search term was successfully created.'
      else
        render :new
      end
    end
  end

  def update
    if @search_term.update(search_term_params)
      redirect_to search_terms_url, notice: 'Search term was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @search_term.destroy
    redirect_to search_terms_url, notice: 'Search term was successfully destroyed.'
  end

  private
    def set_search_term
      @search_term = SearchTerm.find(params[:id])
    end

    def search_term_params
      params.require(:search_term).permit(:query)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def profiles
    @profiles = Profile.search(params[:query])

    respond_to do |format|
      format.html { @profiles = @profiles.paginate(:page => params[:page], :per_page => 30) }
      format.xlsx
    end
  end

  def search
    @terms = SearchTerm.where(searched: false)
    SearchService.run
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_terms_helper.rb
module SearchTermsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_admin_bar.html.erb
<div class="admin-bar">
  <h2>Admin</h2>
  <hr>
  <ul>
    <li><%= link_to "About", root_path %></li>
    <li><%= link_to "Profiles", profiles_path %></li>
    <li><%= link_to "Search Terms", search_terms_path %></li>
    <li><%= link_to "Create Terms", new_search_term_path %></li>
  </ul>
</div>

app/views/layouts/_error_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />

    <!-- Compressed CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/foundation-sites@6.5.0/dist/css/foundation.min.css" integrity="sha256-VEEaOnBKVRoYPn4AID/tY/XKVxKEqXstoo/xZ6nemak= sha384-D46t32f421/hB30qwnim2pIcisNN5GU9+6m2Mfnd3dKpTSFidZLa08/1StEiCFId sha512-WkgzH8VKemDfwrp18r+wgbx+oHXOkfd2kJs7ocAXdGDgonXDXh88E90IRtRZRXtO0IHprxYHYlY14h+wyTsUDA==" crossorigin="anonymous">

    <!-- Compressed JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/foundation-sites@6.5.0/dist/js/foundation.min.js" integrity="sha256-GZq6aeugpWo25iH//1eKmeK6FHCf+6KXTfoUpkCqPCA= sha384-vjxUQtbGw5FJMigaaFpXYyxoHHLb7LbvRywnMZOiPJeh5j9sl2rnmQ3iucuegRm8 sha512-h7tIMIX/opZXfWkcTDbkO+nT0LePyAAwDacfYhWtgGUidV+Kkh3eesW52fPSxKEsw3rgywKhQvghNLT4eDuUyw==" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

  </head>

  <body>
    <div class="body">
      <%= render 'layouts/admin_bar' %>
      <div class="content">
        <%= render 'layouts/error_messages' %>

        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/search_terms/_form.html.erb
<div class="search terms-search">
  <%= form_with(model: search_term, local: true) do |form| %>
    <% if search_term.errors.any? %>
      <div id="error_explanation">
        <h4>Error</h4>

        <ul>
        <% search_term.errors.full_messages.each_with_index do |message| %>

          <li style="list-style: none; font-size: .75rem; margin: 0"><b><%= index =+ 1 %>)</b> <%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>


    <div class="field">
      <%= form.label "Enter Query" %>
      <%= form.text_area :query, size: "60x3" %>
    </div>

    <div class="actions">
      <%= form.submit "SUBMIT" %>
    </div>
  <% end %>
</div>

app/views/search_terms/edit.html.erb
<h4>Edit Search Term</h4>
<%= render 'form', search_term: @search_term %>

app/views/search_terms/index.html.erb
<% if @search_terms %>
  <h4>Search Terms (<%= @search_terms.count %>)</h4>

  <div class="terms">
    <% @search_terms.each do |search_term| %>
      <div class="term">
        <div>
          <b>Query:</b> <%= search_term.query %>
        </div>
        <div>
          <b>Active Search:</b>
          <% if search_term.searched %>
            No
          <% else %>
            Yes
          <% end %>
        </div>
        <% if search_term.bookmark.blank? %>
          <div><b>Bookmark:</b> No</div>
        <% else %>
          <div>
            <b>Bookmark Page: </b><%= search_term.bookmark.page_number %>
            <div class="bookmark-url">
              <b>Bookmark URL:</b>
              <% unless search_term.bookmark.url %>
                N/A
              <% else %>
                <%= search_term.bookmark.url %>
              <% end %>
            </div>
          </div>
        <% end %>

        <%= link_to 'EDIT', edit_search_term_path(search_term), class: "button" %>
        <%= link_to 'DELETE', search_term, method: :delete, data: { confirm: 'Are you sure?' },
                                           class: "button delete-button" %>
      </div>

    <% end %>
  </div>
<% else %>
  <h2 style="text-align: center">There are no profiles.</h2>
<% end %>

<%= will_paginate @search_terms, inner_window: 1, outer_window: 1 %>

app/views/search_terms/new.html.erb
<h4>New Search Term</h4>
<%= render 'form', search_term: @search_term %>

<div class="search terms-search" style="margin-top: 9.375rem;">
  <h5>Import Spreadsheet</h5>
  <%= form_tag search_terms_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "UPLOAD" %>
  <% end %>
</div>

app/views/static_pages/about.html.erb
<div class="about-bar">
  <li><b>Guide</b></li>
  <li onclick="getElementById('walkthrough').scrollIntoView();">Walkthrough</li>
  <li onclick="getElementById('scrape').scrollIntoView();">Scrape</li>
  <li onclick="getElementById('single-search').scrollIntoView();">Enter Single Term</li>
  <li onclick="getElementById('multiple-search').scrollIntoView();">Import Terms</li>
  <li onclick="getElementById('search-profiles').scrollIntoView(false);">Search Profiles</li>
  <li onclick="getElementById('download-profiles').scrollIntoView();">Download Profiles</li>
  <br/>
  <li><b>About</b></li>
  <li onclick="getElementById('multiple-applications').scrollIntoView();">Multiple Apps</li>
  <li onclick="getElementById('trigger-script').scrollIntoView();">Trigger Script</li>
  <li onclick="getElementById('shared-database').scrollIntoView();">Shared Database</li>
  <li onclick="getElementById('searching').scrollIntoView();">Searching</li>
</div>


<div class="about-content">
  <div class="about-collection-div">
    <div class="about-div">
      <p>This web application is designed to scrape Google and save the results to the database as profiles. It will use the search queries that you enter and return the emails it finds within those queries.</p><br/>

      <h4>How It Works</h4>
      <p>There are 5 identical web applications that are on different Heroku servers.<br/>
      In any of the Heroku web application you can create search terms to be scraped.<br/>
      All the web applications share the same database so terms and results are shared amongst all web applications.<br/>
      There is a “trigger” script that you download and run locally, it iterates through each Heroku server scraping Google.<br/>
      After the program is done scraping, you can download the data to an Excel file from any of the 5 Heroku web applications.</p>
    </div>
  </div>

  <div class="about-collection-div">
    <h2>Guide</h2>
    <div class="about-div" id="walkthrough">
      <h4>Walkthrough Example</h4>
      <p>With the "trigger" script.</p>
      <ol>
        <li>Download the "trigger" script -
          <%= link_to 'here', 'https://github.com/sean-nc/fin_scrape_trig', target: '_blank' %>.
        </li>
        <li>Go to
          <%= link_to "Fintros Scraper", 'https://finscrap1.herokuapp.com/search_terms/new', target: '_blank' %>.
        </li>
        <li>Enter a new search term in the "Enter query" text area.</li>
        <li>Click the "submit" button.</li>
        <li>Open up your computer's terminal</li>
        <li>In your terminal, navigate to the folder that has the "trigger" script.</li>
        <li>Type "ruby scrape_trigger.rb" into the terminal and press enter.</li>
      </ol>
      <p>Through the "trigger" website.</p>
      <ol>
        <li>Go to
          <%= link_to "Fintros Scraper", 'https://finscrap1.herokuapp.com/search_terms/new', target: '_blank' %>.
        </li>
        <li>Enter a new search term in the "Enter query" text area.</li>
        <li>Click the "submit" button.</li>
        <li>Go to the
          <%= link_to 'Trigger Site', 'https://fintrigger.herokuapp.com/', target: '_blank' %>.
        </li>
        <li>Click "search".</li>
        <li>The webpage will load until it is done scraping.</li>
      </ol>
    </div>

    <div class="about-div" id="single-search">
      <h4>How To Create a Single Search Term</h4>
      <ol>
        <li>Go to
          <%= link_to "create new term",
              'https://finscrap1.herokuapp.com/search_terms/new', target: '_blank' %>.
        </li>
        <li>Fill out the "Enter query" text area with the query you want to search for.</li>
        <li>Click "submit".</li>
        <li>Your search term has been created.</li>
      </ol>
    </div>

    <div class="about-div" id="multiple-search">
      <h4>How To Import an Excel Spreadsheet of Terms</h4>
      <ol>
        <li>Locally, create a new Excel spreadsheet.</li>
        <li>Add only one search term per line. Enter them exactly how you would in Google search.</li>
        <li>Save locally as .xlsx or .xls.</li>
        <li>Go to
          <%= link_to "create new term",
              'https://finscrap1.herokuapp.com/search_terms/new', target: '_blank' %>.
        </li>
        <li>Under "Import Spreadsheets", click on the "Choose file" button.</li>
        <li>Select the Excel file you wish to import.</li>
        <li>Click "Upload".</li>
        <li>Your new search terms have been created.</li>
      </ol>
    </div>

    <div class="about-div" id="scrape">
      <h4>How To Scrape</h4>
      <p>With the "trigger" script.</p>
      <ol>
        <li>Download the “trigger” script -
          <%= link_to 'here', 'https://github.com/sean-nc/fin_scrape_trig', target: '_blank' %>.
        </li>
        <li>Open your terminal.</li>
        <li>In your terminal, go to the folder that has the "trigger" script.</li>
        <li>Type “ruby scrape_trigger.rb” into the terminal and press enter.</li>
      </ol>
      <p>Through the "trigger" website.</p>
      <ol>
        <li>Go to the
          <%= link_to 'Trigger Site', 'https://fintrigger.herokuapp.com/', target: '_blank' %>.
        </li>
        <li>Click "search".</li>
        <li>The webpage will load until it is done scraping.</li>
      </ol>
    </div>

    <div class="about-div" id="search-profiles">
      <h4>How To Search Profiles</h4>
      <ol>
        <li>Go to the
          <%= link_to "profiles page",
              'https://finscrap1.herokuapp.com/profiles', target: '_blank' %>.
        </li>
        <li>Enter the name or email you wish to find into the search bar.</li>
        <li>Click "search".</li>
        <li>All profiles containing the name or email will show.</li>
      </ol>
    </div>

    <div class="about-div" id="download-profiles">
      <h4>How To Download Profiles</h4>
      <ol>
        <li>Go to the
          <%= link_to "profiles page",
              'https://finscrap1.herokuapp.com/profiles', target: '_blank' %>.
        </li>
        <li>Scroll to the bottom of the page.</li>
        <li>Click on the "Download as .xlsx" button.</li>
        <li>The profiles will download as an Excel spreadsheet.</li>
      </ol>
    </div>
  </div>

  <div class="about-collection-div">
    <h2>About</h2>
    <div class="about-div" id="multiple-applications">
      <h4>Multiple Heroku Applications</h4>
      <p>There are multiple web applications (all identical) on Heroku because Google blocks the server's IP if it believes it is making robotic movements. Everytime one of the web application is blocked, the Heroku server restarts, this resets the IP, making it able to crawl Google again.</p>
    </div>

    <div class="about-div" id="trigger-script">
      <h4>Trigger Script</h4>
      <p>The script was created to run locally to control the search function of the Heroku web applications. The purpose of the “trigger” script is that when a web application gets blocked by Google, the “trigger” script moves to the next web application. The array of Heroku web applications are in a loop that runs until there are no search terms left to be searched. There are delays in the “trigger” script to allow for the Heroku servers to restart before being used again.</p>
    </div>

    <div class="about-div" id="shared-database">
      <h4>Shared Database</h4>
      <p>All the Heroku web applications share a single database. This means that all the results and the search terms are accessible on any of the Heroku web applications. This also adds for validation that each query and email is unique.</p>
    </div>

    <div class="about-div" id="searching">
      <h4>Scraping</h4>
      <p>It is suggested that you use the “trigger” script that I’ve provided. However, I've set up a "trigger" site
          <%= link_to 'here', 'https://fintrigger.herokuapp.com/', target: '_blank' %>.
          You can also scrape terms this way. I suggest the local script, because I don't know if Heroku will shut down the "trigger" server if you're in a loop for hours.
      </p>
    </div>
  </div>
</div>

app/views/static_pages/profiles.html.erb
<div class="search">
  <%= form_tag('/profiles', method: :get) do %>
    <h4>Search Profiles</h4>
    <p>please enter a name or email</p>
    <%= text_field_tag(:query) %>

    <%= submit_tag('SEARCH') %>
  <% end %>
</div>

<% if @profiles.blank? %>
  <h2 style="text-align: center">There are no profiles.</h2>
<% else %>
  <h4>Profiles (<%= @profiles.count %>)</h4>

  <div class="profiles">
    <% @profiles.each do |profile| %>
      <div class="profile">
        <div><b>ID:</b> <%= profile.id %></div>
        <div><b>Email:</b> <%= profile.email %></div>
        <div><b>Title:</b> <%= profile.title %></div>
      </div>
    <% end %>
  </div>


  <%= link_to "Download as .xlsx (#{@profiles.count} profiles)",
              profiles_path(format: :xlsx, query: params[:query]), class: "button" %>

  <%= will_paginate @profiles, inner_window: 1, outer_window: 1 %>
<% end %>

app/views/static_pages/search.html.erb
<% if @terms.blank? %>
  <h2 style="text-align: center; margin: 12.5rem 0">All Terms Have Been Searched</h2>
<% end %>